apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: task-tracker-prod

patchesStrategicMerge:
- replica-patch.yaml
- resource-patch.yaml

commonLabels:
  environment: prod
