# Task Tracker Application Configuration

# Image configurations - GitHub Actions tarafından otomatik güncellenir
images:
  backend:
    repository: bakiakgun/task-tracker-backend
    tag: "bf281aeb"  # Bu tag GitHub Actions tarafından güncellenecek
    pullPolicy: IfNotPresent
  frontend:
    repository: bakiakgun/task-tracker-frontend
    tag: "bf281aeb"  # Bu tag GitHub Actions tarafından güncellenecek
    pullPolicy: IfNotPresent

# Replica configurations
replicaCount:
  backend: 1
  frontend: 1

# Service configurations
service:
  backend:
    type: ClusterIP
    port: 8000
    targetPort: 8000
  frontend:
    type: LoadBalancer
    port: 3000
    targetPort: 3000

# Resource configurations
resources:
  backend:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  frontend:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

# Environment variables
env:
  backend:
    PYTHONPATH: "/app"
    ENVIRONMENT: "development"
  frontend:
    REACT_APP_API_URL: "http://task-tracker-backend-service:8000"

# Health checks
healthCheck:
  backend:
    enabled: true
    path: "/health"
    initialDelaySeconds: 30
    periodSeconds: 10
  frontend:
    enabled: true
    path: "/"
    initialDelaySeconds: 30
    periodSeconds: 10

# Namespace (ArgoCD tarafından override edilecek)
namespace: task-tracker-dev

# Labels
labels:
  app: task-tracker
  project: task-tracker
  managed-by: argocd
