apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: my-app
data:
  APP_ENV: "production"
  DATABASE_URL: "postgresql://db:5432/myapp"
  API_BASE_URL: "http://backend-service:3001"
  FRONTEND_PORT: "80"
  BACKEND_PORT: "3001"
