apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "task-tracker.fullname" . }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "task-tracker.labels" . | nindent 4 }}
    component: backend
spec:
  replicas: {{ .Values.replicaCount.backend }}
  selector:
    matchLabels:
      {{- include "task-tracker.selectorLabels" . | nindent 6 }}
      component: backend
  template:
    metadata:
      labels:
        {{- include "task-tracker.selectorLabels" . | nindent 8 }}
        component: backend
    spec:
      containers:
      - name: backend
        image: "{{ .Values.images.backend.repository }}:{{ .Values.images.backend.tag }}"
        imagePullPolicy: {{ .Values.images.backend.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.backend.targetPort }}
          protocol: TCP
        env:
        {{- range $key, $value := .Values.env.backend }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- if .Values.healthCheck.backend.enabled }}
        livenessProbe:
          httpGet:
            path: {{ .Values.healthCheck.backend.path }}
            port: http
          initialDelaySeconds: {{ .Values.healthCheck.backend.initialDelaySeconds }}
          periodSeconds: {{ .Values.healthCheck.backend.periodSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.healthCheck.backend.path }}
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        {{- end }}
        resources:
          {{- toYaml .Values.resources.backend | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "task-tracker.fullname" . }}-backend-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "task-tracker.labels" . | nindent 4 }}
    component: backend
spec:
  type: {{ .Values.service.backend.type }}
  ports:
  - port: {{ .Values.service.backend.port }}
    targetPort: {{ .Values.service.backend.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "task-tracker.selectorLabels" . | nindent 4 }}
    component: backend
