apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-tracker-backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount.backend }}
  selector:
    matchLabels:
      app: task-tracker-backend
  template:
    metadata:
      labels:
        app: task-tracker-backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.images.backend.repository }}:{{ .Values.images.backend.tag }}
        ports:
        - containerPort: 8000
