apiVersion: v1
kind: Service
metadata:
  name: task-tracker-backend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: task-tracker-backend
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
