apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-tracker-frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount.frontend }}
  selector:
    matchLabels:
      app: task-tracker-frontend
  template:
    metadata:
      labels:
        app: task-tracker-frontend
    spec:
      containers:
      - name: frontend
        image: {{ .Values.images.frontend.repository }}:{{ .Values.images.frontend.tag }}
        ports:
        - containerPort: 3000
