name: CI/CD Pipeline

on:
  push:
    branches:
      - master

env:
  SHORT_SHA: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code (with submodules)
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker Hub Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push Backend Image
      uses: docker/build-push-action@v4
      with:
        context: ./task-tracker-backend
        push: true
        tags: |
          bakiakgun/task-tracker-backend:${{ env.SHORT_SHA }}
    
    - name: Build & Push Frontend Image
      uses: docker/build-push-action@v4
      with:
        context: ./task-tracker-frontend
        push: true
        tags: |
          bakiakgun/task-tracker-frontend:${{ env.SHORT_SHA }}

    - name: Replace image tags in deployment files
      run: |
        find backend -type f -name '*.yml' -exec sed -i "s|{{IMAGE_TAG}}|${SHORT_SHA}|" {} \;
        find frontend -type f -name '*.yml' -exec sed -i "s|{{IMAGE_TAG}}|${SHORT_SHA}|" {} \;

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > ~/.kube/config

    - name: Apply Kubernetes Manifests
      run: |
        kubectl apply -f namespace.yml
        kubectl apply -f backend/
        kubectl apply -f frontend/
