apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- backend-deployment.yaml
- frontend-deployment.yaml
- ingress.yaml

commonLabels:
  project: task-tracker
  managed-by: argocd

namespace: task-tracker
