name: Build and Push Docker Images

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_USER: bakiakgun

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Get commit hash
      id: commit
      run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push backend
      uses: docker/build-push-action@v5
      with:
        context: ./task-tracker-backend
        push: true
        tags: |
          ${{ env.DOCKER_USER }}/task-tracker-backend:${{ steps.commit.outputs.hash }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Build and push frontend
      uses: docker/build-push-action@v5
      with:
        context: ./task-tracker-frontend
        push: true
        tags: |
          ${{ env.DOCKER_USER }}/task-tracker-frontend:${{ steps.commit.outputs.hash }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Update deployment files
      run: |
        echo "COMMIT_HASH=${{ steps.commit.outputs.hash }}" > deployment.env
        echo "Backend image: ${{ env.DOCKER_USER }}/task-tracker-backend:${{ steps.commit.outputs.hash }}"
        echo "Frontend image: ${{ env.DOCKER_USER }}/task-tracker-frontend:${{ steps.commit.outputs.hash }}"
